### ISSUE TITLE
Need help with errors

### ISSUE THREAD

**Issue by JonathanSankey** [buseamy/GR-JCI#17]
editor_configure_submission_dates.php:
- Use to work but changes were made some where on the website and I can no longer get the dates to submit correctly. No matter what I do it says the date is in the wrong format every time.

create_announcement.php:
- displays correctly but has a string conversion error revolving around the roles array. I can't figure out exactly what the problem is.

**Comment by MitchSpencerF17** [comment]
create_announcement.php - spAnnouncementAddRole is expecting ID integers for both values, remove the single-quotes around the values in the call.

**Comment by JonathanSankey** [comment]
I just did that and still get the same error:

Catchable fatal error: Object of class mysqli_result could not be converted to string in C:\xampp\htdocs\create_announcement.php on line 71

**Comment by MitchSpencerF17** [comment]
line 64, $announcementID is assigned the result object of spCreateAnnouncement

**Comment by MitchSpencerF17** [comment]
editor_configure_submission_dates.php - regex is wrong, last segment is looking for 19 OR 20, in addition to whatever else is preventing it from matching.

**Comment by MitchSpencerF17** [comment]
additionally, save the regex to a variable instead of having the same one copied everywhere - Copy&Paste error potential

**Comment by JonathanSankey** [comment]
alright I fixed the first issue by switching from regex to checkdate().

now the issue I'm having with create_anouncement.php is with displaying all the user roles:
-Fatal error: Uncaught Error: Call to a member function fetch_assoc() on boolean in C:\xampp\htdocs\create_announcement.php:113 Stack trace: #0 {main} thrown in C:\xampp\htdocs\create_announcement.php on line 113
